language: R
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel

env:
  global:
    - secure: "Z0H3MztYhbCNfJDpBCnHBCPOVD304une4N7dp9IMYqWk8uzS3qxeuDc6FufIlRAMfiHmpOYA3wIQqWTxKQDtEzUyr/CeJgWMkfcvQlMItTkNN2Y5l90+nQ0lClUqOxy287pfa1+CqP9GJ+i9OzYO9620fymWDhhBDFjuNriAH9V8z2LXdYiO6gAWDApkNpr1RIh3P8mcstIdPKFHe4+6mPocHjgR0pV8jjlDuFD/qAgnS8pgcgxEzmnuKUkJk60R4YSTEf+0pat8G+nJy4Pv9wQCboJFH2QRQDhj9EwsCqcW0vQDqo4fb1evcYKYR/yGGlTAsLrdhZzS8jP2nC8Enj4fVylvc+v2CoBxy0aEX4zaZ/LulNxwJ7rsEVDlpsIPzA28MVjjC/2MuZLi4OKHQeJ4LFo0RtZAOO+EcVG+uSiSxb6zTtWT6S3/hYzQbiwRjlJBgGZk/Bfa9Smk82i5UZaL9di5bA0ci/F2CGlpQadsQ4n9ZnCAsdBeRX7V5t5H3XxGrnv0PfyxA1XTC4v4CWBNNnShKrbXdjKSV9nMzXRccjQ8Mgu/iD7uFuO6diOX3XGA/kmeIi/dq3wY1p2RJTsItfmKC7rlHdt0UTW4HEAqGZWenYxuG4RszmQlPj0YmwCCHy+Q8QIX6PZXAl5OGATuusGZsZOgSQjSipHO7w8="