title:            rscorecard
tagline:          'R package'
description:      'A Method to Download Department of Education College Scorecard Data'
github:		  https://github.com/btskinner/rscorecard
version:	  0.2.5
baseurl: 	  "/rscorecard"

author:
  name:           'Benjamin Skinner'
  url:            http://btskinner.me

highlighter:      rouge
permalink:        pretty


